/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as TestTestPageRouteImport } from './routes/test/test-page'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthChangePasswordRouteImport } from './routes/auth/change-password'
import { Route as ProtectedTutorIndexRouteImport } from './routes/_protected/tutor/index'
import { Route as ProtectedStudentIndexRouteImport } from './routes/_protected/student/index'
import { Route as ProtectedStaffIndexRouteImport } from './routes/_protected/staff/index'
import { Route as ProtectedStaffHomeRouteImport } from './routes/_protected/staff/home'
import { Route as ProtectedStaffTutorsIndexRouteImport } from './routes/_protected/staff/tutors/index'
import { Route as ProtectedStaffStudentsIndexRouteImport } from './routes/_protected/staff/students/index'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestPageRoute = TestTestPageRouteImport.update({
  id: '/test/test-page',
  path: '/test/test-page',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/auth/change-password',
  path: '/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTutorIndexRoute = ProtectedTutorIndexRouteImport.update({
  id: '/tutor/',
  path: '/tutor/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStudentIndexRoute = ProtectedStudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStaffIndexRoute = ProtectedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStaffHomeRoute = ProtectedStaffHomeRouteImport.update({
  id: '/staff/home',
  path: '/staff/home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStaffTutorsIndexRoute =
  ProtectedStaffTutorsIndexRouteImport.update({
    id: '/staff/tutors/',
    path: '/staff/tutors/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedStaffStudentsIndexRoute =
  ProtectedStaffStudentsIndexRouteImport.update({
    id: '/staff/students/',
    path: '/staff/students/',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedRouteWithChildren
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/test/test-page': typeof TestTestPageRoute
  '/test/': typeof TestIndexRoute
  '/staff/home': typeof ProtectedStaffHomeRoute
  '/staff/': typeof ProtectedStaffIndexRoute
  '/student/': typeof ProtectedStudentIndexRoute
  '/tutor/': typeof ProtectedTutorIndexRoute
  '/staff/students/': typeof ProtectedStaffStudentsIndexRoute
  '/staff/tutors/': typeof ProtectedStaffTutorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedRouteWithChildren
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/test/test-page': typeof TestTestPageRoute
  '/test': typeof TestIndexRoute
  '/staff/home': typeof ProtectedStaffHomeRoute
  '/staff': typeof ProtectedStaffIndexRoute
  '/student': typeof ProtectedStudentIndexRoute
  '/tutor': typeof ProtectedTutorIndexRoute
  '/staff/students': typeof ProtectedStaffStudentsIndexRoute
  '/staff/tutors': typeof ProtectedStaffTutorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/test/test-page': typeof TestTestPageRoute
  '/test/': typeof TestIndexRoute
  '/_protected/staff/home': typeof ProtectedStaffHomeRoute
  '/_protected/staff/': typeof ProtectedStaffIndexRoute
  '/_protected/student/': typeof ProtectedStudentIndexRoute
  '/_protected/tutor/': typeof ProtectedTutorIndexRoute
  '/_protected/staff/students/': typeof ProtectedStaffStudentsIndexRoute
  '/_protected/staff/tutors/': typeof ProtectedStaffTutorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/change-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/test/test-page'
    | '/test/'
    | '/staff/home'
    | '/staff/'
    | '/student/'
    | '/tutor/'
    | '/staff/students/'
    | '/staff/tutors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/change-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/test/test-page'
    | '/test'
    | '/staff/home'
    | '/staff'
    | '/student'
    | '/tutor'
    | '/staff/students'
    | '/staff/tutors'
  id:
    | '__root__'
    | '/_protected'
    | '/auth/change-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/test/test-page'
    | '/test/'
    | '/_protected/staff/home'
    | '/_protected/staff/'
    | '/_protected/student/'
    | '/_protected/tutor/'
    | '/_protected/staff/students/'
    | '/_protected/staff/tutors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  TestTestPageRoute: typeof TestTestPageRoute
  TestIndexRoute: typeof TestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/test-page': {
      id: '/test/test-page'
      path: '/test/test-page'
      fullPath: '/test/test-page'
      preLoaderRoute: typeof TestTestPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/auth/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tutor/': {
      id: '/_protected/tutor/'
      path: '/tutor'
      fullPath: '/tutor/'
      preLoaderRoute: typeof ProtectedTutorIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/student/': {
      id: '/_protected/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof ProtectedStudentIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/staff/': {
      id: '/_protected/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof ProtectedStaffIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/staff/home': {
      id: '/_protected/staff/home'
      path: '/staff/home'
      fullPath: '/staff/home'
      preLoaderRoute: typeof ProtectedStaffHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/staff/tutors/': {
      id: '/_protected/staff/tutors/'
      path: '/staff/tutors'
      fullPath: '/staff/tutors/'
      preLoaderRoute: typeof ProtectedStaffTutorsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/staff/students/': {
      id: '/_protected/staff/students/'
      path: '/staff/students'
      fullPath: '/staff/students/'
      preLoaderRoute: typeof ProtectedStaffStudentsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedStaffHomeRoute: typeof ProtectedStaffHomeRoute
  ProtectedStaffIndexRoute: typeof ProtectedStaffIndexRoute
  ProtectedStudentIndexRoute: typeof ProtectedStudentIndexRoute
  ProtectedTutorIndexRoute: typeof ProtectedTutorIndexRoute
  ProtectedStaffStudentsIndexRoute: typeof ProtectedStaffStudentsIndexRoute
  ProtectedStaffTutorsIndexRoute: typeof ProtectedStaffTutorsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedStaffHomeRoute: ProtectedStaffHomeRoute,
  ProtectedStaffIndexRoute: ProtectedStaffIndexRoute,
  ProtectedStudentIndexRoute: ProtectedStudentIndexRoute,
  ProtectedTutorIndexRoute: ProtectedTutorIndexRoute,
  ProtectedStaffStudentsIndexRoute: ProtectedStaffStudentsIndexRoute,
  ProtectedStaffTutorsIndexRoute: ProtectedStaffTutorsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  TestTestPageRoute: TestTestPageRoute,
  TestIndexRoute: TestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
