/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as TestTestPageRouteImport } from './routes/test/test-page'
import { Route as TestOkRouteImport } from './routes/test/ok'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthChangePasswordRouteImport } from './routes/auth/change-password'
import { Route as TestRyan2IndexRouteImport } from './routes/test/ryan2/index'
import { Route as TestRyanIndexRouteImport } from './routes/test/ryan/index'
import { Route as TestNathanIndexRouteImport } from './routes/test/nathan/index'
import { Route as TestMessagesIndexRouteImport } from './routes/test/messages/index'
import { Route as TestJohn2IndexRouteImport } from './routes/test/John2/index'
import { Route as ProtectedTutorIndexRouteImport } from './routes/_protected/tutor/index'
import { Route as ProtectedStudentIndexRouteImport } from './routes/_protected/student/index'
import { Route as ProtectedStaffIndexRouteImport } from './routes/_protected/staff/index'
import { Route as TestNathanHomeRouteImport } from './routes/test/nathan/home'
import { Route as TestJohn2LoginRouteImport } from './routes/test/John2/login'
import { Route as TestJohn2AddUserRouteImport } from './routes/test/John2/add-user'
import { Route as ProtectedStaffHomeRouteImport } from './routes/_protected/staff/home'
import { Route as ProtectedTutorStudentsIndexRouteImport } from './routes/_protected/tutor/students/index'
import { Route as ProtectedStaffTutorsIndexRouteImport } from './routes/_protected/staff/tutors/index'
import { Route as ProtectedStaffStudentsIndexRouteImport } from './routes/_protected/staff/students/index'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestPageRoute = TestTestPageRouteImport.update({
  id: '/test/test-page',
  path: '/test/test-page',
  getParentRoute: () => rootRouteImport,
} as any)
const TestOkRoute = TestOkRouteImport.update({
  id: '/test/ok',
  path: '/test/ok',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/auth/change-password',
  path: '/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRyan2IndexRoute = TestRyan2IndexRouteImport.update({
  id: '/test/ryan2/',
  path: '/test/ryan2/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRyanIndexRoute = TestRyanIndexRouteImport.update({
  id: '/test/ryan/',
  path: '/test/ryan/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestNathanIndexRoute = TestNathanIndexRouteImport.update({
  id: '/test/nathan/',
  path: '/test/nathan/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestMessagesIndexRoute = TestMessagesIndexRouteImport.update({
  id: '/test/messages/',
  path: '/test/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestJohn2IndexRoute = TestJohn2IndexRouteImport.update({
  id: '/test/John2/',
  path: '/test/John2/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTutorIndexRoute = ProtectedTutorIndexRouteImport.update({
  id: '/tutor/',
  path: '/tutor/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStudentIndexRoute = ProtectedStudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStaffIndexRoute = ProtectedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => ProtectedRoute,
} as any)
const TestNathanHomeRoute = TestNathanHomeRouteImport.update({
  id: '/test/nathan/home',
  path: '/test/nathan/home',
  getParentRoute: () => rootRouteImport,
} as any)
const TestJohn2LoginRoute = TestJohn2LoginRouteImport.update({
  id: '/test/John2/login',
  path: '/test/John2/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TestJohn2AddUserRoute = TestJohn2AddUserRouteImport.update({
  id: '/test/John2/add-user',
  path: '/test/John2/add-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedStaffHomeRoute = ProtectedStaffHomeRouteImport.update({
  id: '/staff/home',
  path: '/staff/home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTutorStudentsIndexRoute =
  ProtectedTutorStudentsIndexRouteImport.update({
    id: '/tutor/students/',
    path: '/tutor/students/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedStaffTutorsIndexRoute =
  ProtectedStaffTutorsIndexRouteImport.update({
    id: '/staff/tutors/',
    path: '/staff/tutors/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedStaffStudentsIndexRoute =
  ProtectedStaffStudentsIndexRouteImport.update({
    id: '/staff/students/',
    path: '/staff/students/',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/test/ok': typeof TestOkRoute
  '/test/test-page': typeof TestTestPageRoute
  '/test/': typeof TestIndexRoute
  '/staff/home': typeof ProtectedStaffHomeRoute
  '/test/John2/add-user': typeof TestJohn2AddUserRoute
  '/test/John2/login': typeof TestJohn2LoginRoute
  '/test/nathan/home': typeof TestNathanHomeRoute
  '/staff/': typeof ProtectedStaffIndexRoute
  '/student/': typeof ProtectedStudentIndexRoute
  '/tutor/': typeof ProtectedTutorIndexRoute
  '/test/John2/': typeof TestJohn2IndexRoute
  '/test/messages/': typeof TestMessagesIndexRoute
  '/test/nathan/': typeof TestNathanIndexRoute
  '/test/ryan/': typeof TestRyanIndexRoute
  '/test/ryan2/': typeof TestRyan2IndexRoute
  '/staff/students/': typeof ProtectedStaffStudentsIndexRoute
  '/staff/tutors/': typeof ProtectedStaffTutorsIndexRoute
  '/tutor/students/': typeof ProtectedTutorStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/test/ok': typeof TestOkRoute
  '/test/test-page': typeof TestTestPageRoute
  '/test': typeof TestIndexRoute
  '/staff/home': typeof ProtectedStaffHomeRoute
  '/test/John2/add-user': typeof TestJohn2AddUserRoute
  '/test/John2/login': typeof TestJohn2LoginRoute
  '/test/nathan/home': typeof TestNathanHomeRoute
  '/staff': typeof ProtectedStaffIndexRoute
  '/student': typeof ProtectedStudentIndexRoute
  '/tutor': typeof ProtectedTutorIndexRoute
  '/test/John2': typeof TestJohn2IndexRoute
  '/test/messages': typeof TestMessagesIndexRoute
  '/test/nathan': typeof TestNathanIndexRoute
  '/test/ryan': typeof TestRyanIndexRoute
  '/test/ryan2': typeof TestRyan2IndexRoute
  '/staff/students': typeof ProtectedStaffStudentsIndexRoute
  '/staff/tutors': typeof ProtectedStaffTutorsIndexRoute
  '/tutor/students': typeof ProtectedTutorStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/test/ok': typeof TestOkRoute
  '/test/test-page': typeof TestTestPageRoute
  '/test/': typeof TestIndexRoute
  '/_protected/staff/home': typeof ProtectedStaffHomeRoute
  '/test/John2/add-user': typeof TestJohn2AddUserRoute
  '/test/John2/login': typeof TestJohn2LoginRoute
  '/test/nathan/home': typeof TestNathanHomeRoute
  '/_protected/staff/': typeof ProtectedStaffIndexRoute
  '/_protected/student/': typeof ProtectedStudentIndexRoute
  '/_protected/tutor/': typeof ProtectedTutorIndexRoute
  '/test/John2/': typeof TestJohn2IndexRoute
  '/test/messages/': typeof TestMessagesIndexRoute
  '/test/nathan/': typeof TestNathanIndexRoute
  '/test/ryan/': typeof TestRyanIndexRoute
  '/test/ryan2/': typeof TestRyan2IndexRoute
  '/_protected/staff/students/': typeof ProtectedStaffStudentsIndexRoute
  '/_protected/staff/tutors/': typeof ProtectedStaffTutorsIndexRoute
  '/_protected/tutor/students/': typeof ProtectedTutorStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/change-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/test/ok'
    | '/test/test-page'
    | '/test/'
    | '/staff/home'
    | '/test/John2/add-user'
    | '/test/John2/login'
    | '/test/nathan/home'
    | '/staff/'
    | '/student/'
    | '/tutor/'
    | '/test/John2/'
    | '/test/messages/'
    | '/test/nathan/'
    | '/test/ryan/'
    | '/test/ryan2/'
    | '/staff/students/'
    | '/staff/tutors/'
    | '/tutor/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/change-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/test/ok'
    | '/test/test-page'
    | '/test'
    | '/staff/home'
    | '/test/John2/add-user'
    | '/test/John2/login'
    | '/test/nathan/home'
    | '/staff'
    | '/student'
    | '/tutor'
    | '/test/John2'
    | '/test/messages'
    | '/test/nathan'
    | '/test/ryan'
    | '/test/ryan2'
    | '/staff/students'
    | '/staff/tutors'
    | '/tutor/students'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth/change-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/test/ok'
    | '/test/test-page'
    | '/test/'
    | '/_protected/staff/home'
    | '/test/John2/add-user'
    | '/test/John2/login'
    | '/test/nathan/home'
    | '/_protected/staff/'
    | '/_protected/student/'
    | '/_protected/tutor/'
    | '/test/John2/'
    | '/test/messages/'
    | '/test/nathan/'
    | '/test/ryan/'
    | '/test/ryan2/'
    | '/_protected/staff/students/'
    | '/_protected/staff/tutors/'
    | '/_protected/tutor/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  TestOkRoute: typeof TestOkRoute
  TestTestPageRoute: typeof TestTestPageRoute
  TestIndexRoute: typeof TestIndexRoute
  TestJohn2AddUserRoute: typeof TestJohn2AddUserRoute
  TestJohn2LoginRoute: typeof TestJohn2LoginRoute
  TestNathanHomeRoute: typeof TestNathanHomeRoute
  TestJohn2IndexRoute: typeof TestJohn2IndexRoute
  TestMessagesIndexRoute: typeof TestMessagesIndexRoute
  TestNathanIndexRoute: typeof TestNathanIndexRoute
  TestRyanIndexRoute: typeof TestRyanIndexRoute
  TestRyan2IndexRoute: typeof TestRyan2IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/test-page': {
      id: '/test/test-page'
      path: '/test/test-page'
      fullPath: '/test/test-page'
      preLoaderRoute: typeof TestTestPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/ok': {
      id: '/test/ok'
      path: '/test/ok'
      fullPath: '/test/ok'
      preLoaderRoute: typeof TestOkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/auth/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/ryan2/': {
      id: '/test/ryan2/'
      path: '/test/ryan2'
      fullPath: '/test/ryan2/'
      preLoaderRoute: typeof TestRyan2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/ryan/': {
      id: '/test/ryan/'
      path: '/test/ryan'
      fullPath: '/test/ryan/'
      preLoaderRoute: typeof TestRyanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/nathan/': {
      id: '/test/nathan/'
      path: '/test/nathan'
      fullPath: '/test/nathan/'
      preLoaderRoute: typeof TestNathanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/messages/': {
      id: '/test/messages/'
      path: '/test/messages'
      fullPath: '/test/messages/'
      preLoaderRoute: typeof TestMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/John2/': {
      id: '/test/John2/'
      path: '/test/John2'
      fullPath: '/test/John2/'
      preLoaderRoute: typeof TestJohn2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tutor/': {
      id: '/_protected/tutor/'
      path: '/tutor'
      fullPath: '/tutor/'
      preLoaderRoute: typeof ProtectedTutorIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/student/': {
      id: '/_protected/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof ProtectedStudentIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/staff/': {
      id: '/_protected/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof ProtectedStaffIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/test/nathan/home': {
      id: '/test/nathan/home'
      path: '/test/nathan/home'
      fullPath: '/test/nathan/home'
      preLoaderRoute: typeof TestNathanHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/John2/login': {
      id: '/test/John2/login'
      path: '/test/John2/login'
      fullPath: '/test/John2/login'
      preLoaderRoute: typeof TestJohn2LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/John2/add-user': {
      id: '/test/John2/add-user'
      path: '/test/John2/add-user'
      fullPath: '/test/John2/add-user'
      preLoaderRoute: typeof TestJohn2AddUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/staff/home': {
      id: '/_protected/staff/home'
      path: '/staff/home'
      fullPath: '/staff/home'
      preLoaderRoute: typeof ProtectedStaffHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tutor/students/': {
      id: '/_protected/tutor/students/'
      path: '/tutor/students'
      fullPath: '/tutor/students/'
      preLoaderRoute: typeof ProtectedTutorStudentsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/staff/tutors/': {
      id: '/_protected/staff/tutors/'
      path: '/staff/tutors'
      fullPath: '/staff/tutors/'
      preLoaderRoute: typeof ProtectedStaffTutorsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/staff/students/': {
      id: '/_protected/staff/students/'
      path: '/staff/students'
      fullPath: '/staff/students/'
      preLoaderRoute: typeof ProtectedStaffStudentsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedStaffHomeRoute: typeof ProtectedStaffHomeRoute
  ProtectedStaffIndexRoute: typeof ProtectedStaffIndexRoute
  ProtectedStudentIndexRoute: typeof ProtectedStudentIndexRoute
  ProtectedTutorIndexRoute: typeof ProtectedTutorIndexRoute
  ProtectedStaffStudentsIndexRoute: typeof ProtectedStaffStudentsIndexRoute
  ProtectedStaffTutorsIndexRoute: typeof ProtectedStaffTutorsIndexRoute
  ProtectedTutorStudentsIndexRoute: typeof ProtectedTutorStudentsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedStaffHomeRoute: ProtectedStaffHomeRoute,
  ProtectedStaffIndexRoute: ProtectedStaffIndexRoute,
  ProtectedStudentIndexRoute: ProtectedStudentIndexRoute,
  ProtectedTutorIndexRoute: ProtectedTutorIndexRoute,
  ProtectedStaffStudentsIndexRoute: ProtectedStaffStudentsIndexRoute,
  ProtectedStaffTutorsIndexRoute: ProtectedStaffTutorsIndexRoute,
  ProtectedTutorStudentsIndexRoute: ProtectedTutorStudentsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  TestOkRoute: TestOkRoute,
  TestTestPageRoute: TestTestPageRoute,
  TestIndexRoute: TestIndexRoute,
  TestJohn2AddUserRoute: TestJohn2AddUserRoute,
  TestJohn2LoginRoute: TestJohn2LoginRoute,
  TestNathanHomeRoute: TestNathanHomeRoute,
  TestJohn2IndexRoute: TestJohn2IndexRoute,
  TestMessagesIndexRoute: TestMessagesIndexRoute,
  TestNathanIndexRoute: TestNathanIndexRoute,
  TestRyanIndexRoute: TestRyanIndexRoute,
  TestRyan2IndexRoute: TestRyan2IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
